sudo: required
dist: trusty
language: bash

stages:
  # - name: Script tests
  - name: Push container
    if: branch = master && type = pull_request
  - name: Check container
    if: branch = master || type = pull_request


services:
  - docker

install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get -qq update

jobs:
  include:
  # - stage: Script tests
  #   script:
  #     - echo ${TRAVIS_COMMIT}
  #     - echo ${TRAVIS_TAG}
  #     - echo ${TRAVIS_BRANCH}
  #     - echo ${TRAVIS_BUILD_NUMBER}
  #     - echo ${TRAVIS_REPO_SLUG}
  #     # test bash scripts
  #     - shellcheck scripts/*.sh
  #     - bashate scripts/*.sh

  - stage: Push container
    script:
      - echo "push to repo"
      - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - VCS_REF=$(git rev-parse --short HEAD)
      - VER=$(cat VERSION)
      - docker build --build-arg BUILD_DATE=${BUILD_DATE} --build-arg VCS_REF=${VCS_REF} --build-arg VER=${VER} -t cfnlint .
      - docker images
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - docker tag cfnlint ${DOCKER_USERNAME}/cfnlint:default
      - docker push ${DOCKER_USERNAME}/cfnlint:default
      #- curl -X POST https://hooks.microbadger.com/images/almerhor/cfnlint/BwefVjGpzAqzhSfbiv-fIq33dd0=
      - docker logout

  - stage: Check container
    script:
      - docker pull ${DOCKER_USERNAME}/cfnlint:default
      - testpath="$(pwd)/tests"
      - docker run --rm -v ${testpath}:/lintfiles ${DOCKER_USERNAME}/cfnlint:default --help
